language: node_js
node_js: node
cache:
  directories:
    - node_modules
services:
  - mongodb
script:
   - npm install 
   - npm test
before_script:
  - sleep 15
  - mongo shoesTest --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

after_success:
  - npm run coverage